# Generated by Django 5.2.12 on 2026-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_profile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='break_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
