--
-- PostgreSQL database dump
--

\restrict wfbEg0D8E98sIUdd9c33WKozOu4NUS9TyE47mEwEObwMpE9YIKIuWSITKx9VAXN

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO attendance_user;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO attendance_user;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO attendance_user;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_attendancecorrectionrequest; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.attendance_attendancecorrectionrequest (
    id bigint NOT NULL,
    date date NOT NULL,
    requested_clock_in timestamp with time zone,
    requested_clock_out timestamp with time zone,
    reason text NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.attendance_attendancecorrectionrequest OWNER TO attendance_user;

--
-- Name: attendance_attendancecorrectionrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.attendance_attendancecorrectionrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_attendancecorrectionrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_attendancerecord; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.attendance_attendancerecord (
    id bigint NOT NULL,
    date date NOT NULL,
    clock_in timestamp with time zone,
    clock_out timestamp with time zone,
    user_id bigint NOT NULL,
    break_minutes integer NOT NULL
);


ALTER TABLE public.attendance_attendancerecord OWNER TO attendance_user;

--
-- Name: attendance_attendancerecord_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.attendance_attendancerecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_attendancerecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_department; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.attendance_department (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.attendance_department OWNER TO attendance_user;

--
-- Name: attendance_department_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.attendance_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_leaverequest; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.attendance_leaverequest (
    id bigint NOT NULL,
    date date NOT NULL,
    reason text NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.attendance_leaverequest OWNER TO attendance_user;

--
-- Name: attendance_leaverequest_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.attendance_leaverequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_leaverequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_overtimerequest; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.attendance_overtimerequest (
    id bigint NOT NULL,
    date date NOT NULL,
    hours numeric(4,2) NOT NULL,
    reason text NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.attendance_overtimerequest OWNER TO attendance_user;

--
-- Name: attendance_overtimerequest_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.attendance_overtimerequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_overtimerequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_profile; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.attendance_profile (
    id bigint NOT NULL,
    employee_id character varying(20),
    department_id bigint,
    manager_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.attendance_profile OWNER TO attendance_user;

--
-- Name: attendance_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.attendance_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO attendance_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO attendance_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO attendance_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO attendance_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO attendance_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO attendance_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: attendance_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: attendance_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO attendance_user;

--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role) FROM stdin;
2		\N	f	testuser				f	t	2026-03-11 10:14:00.850932+00	employee
3		\N	f	signal_test				f	t	2026-03-11 10:30:00.428341+00	employee
5	pbkdf2_sha256$1000000$Gv9Kw6SdB8vXzVTiV9FKTU$Z7iyaSiDPDq/sM/sgiZruEVdluyDuy4vYorqjBP5WpY=	2026-03-23 08:56:06.176169+00	f	User2				f	t	2026-03-23 08:23:44+00	employee
6	pbkdf2_sha256$1000000$vV5p8OSiRYBQq3XAZut3l2$3Kb+Yb6SFSn/Xvi5/1JO/Kw3WsppmeNcuSWGXLVloJ4=	2026-03-23 10:27:57.497948+00	f	Manager1				f	t	2026-03-23 08:25:01+00	manager
1	pbkdf2_sha256$1000000$pzYZs2UuOj5sRtkTnR1hBm$EBikdgB21nuFTF+bQQndmTCgKRfINEZtBkRkRqyu3PU=	2026-03-25 01:20:03.160649+00	t	supper_user				t	t	2026-03-11 09:31:02.589114+00	employee
4	pbkdf2_sha256$1000000$85CVCVbJcibdCZvIot1cOB$6SQelPOCFqPxs9AF1F+BKbgxQJ9x7Br/t8OxAzILDNw=	2026-03-25 01:23:18.052915+00	f	User1				f	t	2026-03-23 08:22:28+00	employee
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: attendance_attendancecorrectionrequest; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.attendance_attendancecorrectionrequest (id, date, requested_clock_in, requested_clock_out, reason, status, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: attendance_attendancerecord; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.attendance_attendancerecord (id, date, clock_in, clock_out, user_id, break_minutes) FROM stdin;
3	2026-03-23	2026-03-23 01:40:14.005492+00	2026-03-23 01:40:20.789063+00	1	60
4	2026-03-23	\N	\N	6	60
\.


--
-- Data for Name: attendance_department; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.attendance_department (id, name) FROM stdin;
1	dev1
2	op1
\.


--
-- Data for Name: attendance_leaverequest; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.attendance_leaverequest (id, date, reason, status, created_at, user_id) FROM stdin;
1	2026-03-24	私用	approved	2026-03-23 02:18:54.322473+00	1
\.


--
-- Data for Name: attendance_overtimerequest; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.attendance_overtimerequest (id, date, hours, reason, status, created_at, user_id) FROM stdin;
1	2026-03-23	1.00		approved	2026-03-23 08:30:50.33304+00	4
2	2026-03-23	2.00		approved	2026-03-23 08:31:05.435334+00	5
3	2026-03-23	3.00		approved	2026-03-23 08:31:25.454938+00	6
4	2026-03-25	1.00		rejected	2026-03-23 10:12:41.827483+00	4
5	2026-03-24	2.00		approved	2026-03-23 10:13:23.019711+00	5
7	2026-03-26	2.00		approved	2026-03-23 10:27:20.877326+00	4
6	2026-03-25	2.00		rejected	2026-03-23 10:26:59.728448+00	4
\.


--
-- Data for Name: attendance_profile; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.attendance_profile (id, employee_id, department_id, manager_id, user_id) FROM stdin;
1		\N	\N	2
2	\N	\N	\N	3
5	\N	\N	\N	6
6	\N	1	6	4
8	\N	2	6	5
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add department	6	add_department
22	Can change department	6	change_department
23	Can delete department	6	delete_department
24	Can view department	6	view_department
25	Can add attendance correction request	7	add_attendancecorrectionrequest
26	Can change attendance correction request	7	change_attendancecorrectionrequest
27	Can delete attendance correction request	7	delete_attendancecorrectionrequest
28	Can view attendance correction request	7	view_attendancecorrectionrequest
29	Can add overtime request	8	add_overtimerequest
30	Can change overtime request	8	change_overtimerequest
31	Can delete overtime request	8	delete_overtimerequest
32	Can view overtime request	8	view_overtimerequest
33	Can add profile	9	add_profile
34	Can change profile	9	change_profile
35	Can delete profile	9	delete_profile
36	Can view profile	9	view_profile
37	Can add attendance record	10	add_attendancerecord
38	Can change attendance record	10	change_attendancerecord
39	Can delete attendance record	10	delete_attendancerecord
40	Can view attendance record	10	view_attendancerecord
41	Can add leave request	11	add_leaverequest
42	Can change leave request	11	change_leaverequest
43	Can delete leave request	11	delete_leaverequest
44	Can view leave request	11	view_leaverequest
45	Can add user	12	add_user
46	Can change user	12	change_user
47	Can delete user	12	delete_user
48	Can view user	12	view_user
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-03-23 01:28:28.57673+00	1	supper_user 2026-03-23	3		10	1
2	2026-03-23 01:40:02.492725+00	2	supper_user 2026-03-23	3		10	1
3	2026-03-23 02:21:08.136169+00	1	supper_user 2026-03-24 休暇申請	2	[{"changed": {"fields": ["Status"]}}]	11	1
4	2026-03-23 08:23:21.342334+00	4	User1	1	[{"added": {}}]	12	1
5	2026-03-23 08:24:45.687622+00	5	User2	1	[{"added": {}}]	12	1
6	2026-03-23 08:25:28.553893+00	6	Manager1	1	[{"added": {}}]	12	1
7	2026-03-23 08:28:41.440781+00	4	User2 profile	3		9	1
8	2026-03-23 08:28:41.440844+00	3	User1 profile	3		9	1
9	2026-03-23 08:29:20.304335+00	1	dev1	1	[{"added": {}}]	6	1
10	2026-03-23 08:29:24.334536+00	6	User1 profile	1	[{"added": {}}]	9	1
11	2026-03-23 08:29:26.450606+00	6	User1 profile	2	[]	9	1
12	2026-03-23 08:29:38.265555+00	7	User2 profile	1	[{"added": {}}]	9	1
13	2026-03-23 08:30:50.337165+00	1	User1 2026-03-23 残業申請	1	[{"added": {}}]	8	1
14	2026-03-23 08:31:05.437338+00	2	User2 2026-03-23 残業申請	1	[{"added": {}}]	8	1
15	2026-03-23 08:31:25.456932+00	3	Manager1 2026-03-23 残業申請	1	[{"added": {}}]	8	1
16	2026-03-23 08:35:22.983032+00	4	User1	2	[]	12	1
17	2026-03-23 08:35:45.823514+00	4	User1	2	[{"changed": {"fields": ["Password"]}}]	12	1
18	2026-03-23 08:36:07.258733+00	5	User2	2	[{"changed": {"fields": ["Password"]}}]	12	1
19	2026-03-23 08:46:16.948331+00	4	User1	2	[]	12	1
20	2026-03-23 08:46:25.035435+00	4	User1	2	[]	12	1
21	2026-03-23 08:46:38.766172+00	6	Manager1	2	[]	12	1
22	2026-03-23 10:12:41.829522+00	4	User1 2026-03-25 残業申請	1	[{"added": {}}]	8	1
23	2026-03-23 10:13:23.020913+00	5	User2 2026-03-24 残業申請	1	[{"added": {}}]	8	1
24	2026-03-23 10:26:59.730538+00	6	User1 2026-03-25 残業申請	1	[{"added": {}}]	8	1
25	2026-03-23 10:27:20.878679+00	7	User1 2026-03-26 残業申請	1	[{"added": {}}]	8	1
26	2026-03-25 01:20:32.017838+00	2	op1	1	[{"added": {}}]	6	1
27	2026-03-25 01:21:49.89836+00	7	User2 profile	3		9	1
28	2026-03-25 01:22:08.603255+00	8	User2 profile	1	[{"added": {}}]	9	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	attendance	department
7	attendance	attendancecorrectionrequest
8	attendance	overtimerequest
9	attendance	profile
10	attendance	attendancerecord
11	attendance	leaverequest
12	accounts	user
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-11 09:22:36.948445+00
2	contenttypes	0002_remove_content_type_name	2026-03-11 09:22:36.991357+00
3	auth	0001_initial	2026-03-11 09:22:37.055877+00
4	auth	0002_alter_permission_name_max_length	2026-03-11 09:22:37.063185+00
5	auth	0003_alter_user_email_max_length	2026-03-11 09:22:37.069076+00
6	auth	0004_alter_user_username_opts	2026-03-11 09:22:37.075237+00
7	auth	0005_alter_user_last_login_null	2026-03-11 09:22:37.083015+00
8	auth	0006_require_contenttypes_0002	2026-03-11 09:22:37.08802+00
9	auth	0007_alter_validators_add_error_messages	2026-03-11 09:22:37.096447+00
10	auth	0008_alter_user_username_max_length	2026-03-11 09:22:37.107924+00
11	auth	0009_alter_user_last_name_max_length	2026-03-11 09:22:37.116898+00
12	auth	0010_alter_group_name_max_length	2026-03-11 09:22:37.129038+00
13	auth	0011_update_proxy_permissions	2026-03-11 09:22:37.135822+00
14	auth	0012_alter_user_first_name_max_length	2026-03-11 09:22:37.142446+00
15	accounts	0001_initial	2026-03-11 09:22:37.219945+00
16	admin	0001_initial	2026-03-11 09:22:37.242307+00
17	admin	0002_logentry_remove_auto_add	2026-03-11 09:22:37.250917+00
18	admin	0003_logentry_add_action_flag_choices	2026-03-11 09:22:37.260319+00
19	attendance	0001_initial	2026-03-11 09:22:37.392633+00
20	sessions	0001_initial	2026-03-11 09:22:37.406209+00
21	attendance	0002_alter_profile_employee_id	2026-03-11 10:28:41.112123+00
22	attendance	0003_attendancerecord_break_minutes	2026-03-16 08:40:52.845406+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: attendance_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
rdovtnb19zjmwlpp5ku8nklyygloavct	.eJxVjEsOwiAUAO_C2hC-D3DpvmcgPHhK1dCktCvj3ZWkC93OTObFYtq3GvdOa5wLOzPDTr8MU35QG6LcU7stPC9tW2fkI-GH7XxaCj0vR_s3qKnXsQWjEbVPFgJ6T1rYLK5A4Mh6hAJoAoAEm4MqUjrSSn15TiikydKx9wfKajcd:1w5Cxq:4RFGccjIGoPgblemI2iKJsCCkV1S20ms9MODoDZwmlU	2026-04-08 01:23:18.056831+00
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 6, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: attendance_attendancecorrectionrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.attendance_attendancecorrectionrequest_id_seq', 1, false);


--
-- Name: attendance_attendancerecord_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.attendance_attendancerecord_id_seq', 4, true);


--
-- Name: attendance_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.attendance_department_id_seq', 2, true);


--
-- Name: attendance_leaverequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.attendance_leaverequest_id_seq', 1, true);


--
-- Name: attendance_overtimerequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.attendance_overtimerequest_id_seq', 7, true);


--
-- Name: attendance_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.attendance_profile_id_seq', 8, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 28, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: attendance_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: attendance_attendancecorrectionrequest attendance_attendancecorrectionrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_attendancecorrectionrequest
    ADD CONSTRAINT attendance_attendancecorrectionrequest_pkey PRIMARY KEY (id);


--
-- Name: attendance_attendancerecord attendance_attendancerecord_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_attendancerecord
    ADD CONSTRAINT attendance_attendancerecord_pkey PRIMARY KEY (id);


--
-- Name: attendance_department attendance_department_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_department
    ADD CONSTRAINT attendance_department_pkey PRIMARY KEY (id);


--
-- Name: attendance_leaverequest attendance_leaverequest_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_leaverequest
    ADD CONSTRAINT attendance_leaverequest_pkey PRIMARY KEY (id);


--
-- Name: attendance_overtimerequest attendance_overtimerequest_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_overtimerequest
    ADD CONSTRAINT attendance_overtimerequest_pkey PRIMARY KEY (id);


--
-- Name: attendance_profile attendance_profile_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_profile
    ADD CONSTRAINT attendance_profile_employee_id_key UNIQUE (employee_id);


--
-- Name: attendance_profile attendance_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_profile
    ADD CONSTRAINT attendance_profile_pkey PRIMARY KEY (id);


--
-- Name: attendance_profile attendance_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_profile
    ADD CONSTRAINT attendance_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: attendance_attendancerecord unique_user_date; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_attendancerecord
    ADD CONSTRAINT unique_user_date UNIQUE (user_id, date);


--
-- Name: attendance_leaverequest unique_user_leave_date; Type: CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_leaverequest
    ADD CONSTRAINT unique_user_leave_date UNIQUE (user_id, date);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: attendance_attendancecorrectionrequest_user_id_3c04f063; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX attendance_attendancecorrectionrequest_user_id_3c04f063 ON public.attendance_attendancecorrectionrequest USING btree (user_id);


--
-- Name: attendance_attendancerecord_user_id_1bb6e31f; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX attendance_attendancerecord_user_id_1bb6e31f ON public.attendance_attendancerecord USING btree (user_id);


--
-- Name: attendance_leaverequest_user_id_c7937bd9; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX attendance_leaverequest_user_id_c7937bd9 ON public.attendance_leaverequest USING btree (user_id);


--
-- Name: attendance_overtimerequest_user_id_7237870d; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX attendance_overtimerequest_user_id_7237870d ON public.attendance_overtimerequest USING btree (user_id);


--
-- Name: attendance_profile_department_id_c8d5aadd; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX attendance_profile_department_id_c8d5aadd ON public.attendance_profile USING btree (department_id);


--
-- Name: attendance_profile_employee_id_7ebd3801_like; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX attendance_profile_employee_id_7ebd3801_like ON public.attendance_profile USING btree (employee_id varchar_pattern_ops);


--
-- Name: attendance_profile_manager_id_a90c2834; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX attendance_profile_manager_id_a90c2834 ON public.attendance_profile USING btree (manager_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: attendance_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_attendancerecord attendance_attendanc_user_id_1bb6e31f_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_attendancerecord
    ADD CONSTRAINT attendance_attendanc_user_id_1bb6e31f_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_attendancecorrectionrequest attendance_attendanc_user_id_3c04f063_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_attendancecorrectionrequest
    ADD CONSTRAINT attendance_attendanc_user_id_3c04f063_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_leaverequest attendance_leaverequest_user_id_c7937bd9_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_leaverequest
    ADD CONSTRAINT attendance_leaverequest_user_id_c7937bd9_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_overtimerequest attendance_overtimerequest_user_id_7237870d_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_overtimerequest
    ADD CONSTRAINT attendance_overtimerequest_user_id_7237870d_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_profile attendance_profile_department_id_c8d5aadd_fk_attendanc; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_profile
    ADD CONSTRAINT attendance_profile_department_id_c8d5aadd_fk_attendanc FOREIGN KEY (department_id) REFERENCES public.attendance_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_profile attendance_profile_manager_id_a90c2834_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_profile
    ADD CONSTRAINT attendance_profile_manager_id_a90c2834_fk_accounts_user_id FOREIGN KEY (manager_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_profile attendance_profile_user_id_12dae504_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.attendance_profile
    ADD CONSTRAINT attendance_profile_user_id_12dae504_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: attendance_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict wfbEg0D8E98sIUdd9c33WKozOu4NUS9TyE47mEwEObwMpE9YIKIuWSITKx9VAXN

